[package]
name = "windows-smtc-monitor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.2", features = ["napi4", "tokio_rt", "async"] }
napi-derive = "2.12.2"
tokio = { version = "1.28.1", features = ["full"] }

[dependencies.windows]
version = "0.48.0"
features = [
  "Foundation",
  "Foundation_Collections",
  "Media_Control",
  "Storage_Streams",
]

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
